cdnUrl = "http://127.0.0.1:8000"
[dingtalk]
  agentid= 1234
  appKey= "xxx"
  appSecret= "xxxx"
  cachePath= "data/store"
[oauth]
    mfa = false
    secret = "oauth_secret"
    salt = 16
    delimiter = "$"
    strectchingPassword = 500
[casbin]
    redisHost = "127.0.0.1:6379"
    redisPwd = ""
    [casbin.rule]
        path = "conf/casbin/rbac_model.conf"
[email]
    isEnable = true
    host = "smtp.exmail.qq.com"
    port = 465
    username = "xxx@website"
    password = "xxx"
    from = "xxx"
    mailExpired = 3600
    mailMaxNum = 3
[muses]
    [muses.server.stat]
        addr = ":19051"
        writeTimeout = "1s"
        readTimeout = "1s"
    [muses.server.gin]
        graceful = true
        mode = "debug"
        addr = ":9051"
        writeTimeout = "10s"
        readTimeout = "10s"
        maxHeaderBytes = 100000000000000
        enabledRecovery = true
        enabledLogger = true
        enabledMetric = true
    [muses.logger.system]
        debug = true
        level = "debug"
        path = "./system.log"
    [muses.mysql.oapms]
        debug = true
        level = "panic"
        network = "tcp"
        dialect = "mysql"
        addr = "127.0.0.1:3306"
        username = "root"
        password = "root"
        db = "oapms"
        charset = "utf8"
        parseTime = "True"
        loc = "Local"
        timeout = "1s"
        readTimeout = "1s"
        writeTimeout = "1s"
        maxOpenConns = 30
        maxIdleConns = 10
        connMaxLifetime = "300s"
    [muses.session.gin]
        mode = "redis" # memory, redis
        name = "mysession"
        size = 10
        debug = true
        network = "tcp"
        addr = "127.0.0.1:6379"
        pwd = ""
        keypairs = "secret"
    [muses.redis.oapms]
        debug = true
        addr = "127.0.0.1:6379"
        network = "tcp"
        db = 0
        password = ""
        connectTimeout = "1s"
        readTimeout = "1s"
        writeTimeout = "1s"
        maxIdle = 5
        maxActive = 20
        idleTimeout = "60s"
        wait = false
